### ISSUE TITLE
Ververica platform cannot start locally

### ISSUE THREAD

**Issue by m-hristova** [ververica/ververica-platform-playground#117]
I am trying to run ververica locally, using the community edition. I tried both with a license and without one. I see that the trial hasn't expired yet

![image](https://github.com/ververica/ververica-platform-playground/assets/29500017/7ba41936-3856-422e-93f7-c73b9e1e8811)

but the following exception is printed in the appmanager and the vvp-ververica-platform pod is in a CrashLoopBackOff:

```Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-10-03 07:09:58.751 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:165) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577) ~[spring-context-5.3.30.jar:5.3.30]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.7.16.jar:2.7.16]
	at com.dataartisans.appmanager.apiserver.AppManagerApplication.main(AppManagerApplication.java:10) ~[app/:na]
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:142) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:481) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:184) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.7.16.jar:2.7.16]
	... 8 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'proxyConfig' defined in file [/vvp/app/com/dataartisans/appmanager/apiserver/config/ProxyConfig.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sslKeyService' defined in class path resource [com/dataartisans/appmanager/controller/core/modules/ServicesModule.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.dataartisans.appmanager.controller.api.services.SslKeyService]: Factory method 'sslKeyService' threw exception; nested exception is java.lang.NoSuchFieldError: id_alg_zlibCompress
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:224) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:405) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:213) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:213) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.getOrderedBeansOfType(ServletContextInitializerBeans.java:204) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.addServletContextInitializerBeans(ServletContextInitializerBeans.java:98) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.ServletContextInitializerBeans.<init>(ServletContextInitializerBeans.java:86) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.getServletContextInitializerBeans(ServletWebServerApplicationContext.java:262) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.selfInitialize(ServletWebServerApplicationContext.java:236) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.springframework.boot.web.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:53) ~[spring-boot-2.7.16.jar:2.7.16]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4904) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:795) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at java.base/java.util.concurrent.AbstractExecutorService.submit(Unknown Source) ~[na:na]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:249) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:922) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:486) ~[tomcat-embed-core-9.0.80.jar:9.0.80]
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123) ~[spring-boot-2.7.16.jar:2.7.16]
	... 13 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sslKeyService' defined in class path resource [com/dataartisans/appmanager/controller/core/modules/ServicesModule.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.dataartisans.appmanager.controller.api.services.SslKeyService]: Factory method 'sslKeyService' threw exception; nested exception is java.lang.NoSuchFieldError: id_alg_zlibCompress
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:633) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$2.resolveCandidate(DefaultListableBeanFactory.java:1849) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.createOptionalDependency(DefaultListableBeanFactory.java:1852) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1298) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:911) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:788) ~[spring-beans-5.3.30.jar:5.3.30]
	... 62 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.dataartisans.appmanager.controller.api.services.SslKeyService]: Factory method 'sslKeyService' threw exception; nested exception is java.lang.NoSuchFieldError: id_alg_zlibCompress
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.30.jar:5.3.30]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-5.3.30.jar:5.3.30]
	... 78 common frames omitted
Caused by: java.lang.NoSuchFieldError: id_alg_zlibCompress
	at org.bouncycastle.asn1.cms.CMSObjectIdentifiers.<clinit>(Unknown Source) ~[bcutil-jdk18on-1.74.jar:1.74.0.0]
	at org.bouncycastle.operator.DefaultSignatureNameFinder.<clinit>(Unknown Source) ~[bcpkix-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.operator.jcajce.OperatorHelper.<clinit>(Unknown Source) ~[bcpkix-jdk15on-1.70.jar:1.70.00.0]
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder.<init>(Unknown Source) ~[bcpkix-jdk15on-1.70.jar:1.70.00.0]
	at com.dataartisans.appmanager.controller.core.ssl.util.SslKeyFactoryBouncyCastle.buildCertificate(SslKeyFactoryBouncyCastle.java:143) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.ssl.util.SslKeyFactoryBouncyCastle.createRootCertificate(SslKeyFactoryBouncyCastle.java:105) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.ssl.KeyCertificatePair.generateRootCertificate(KeyCertificatePair.java:45) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.ssl.SslKeyHolder.generateRootCertAndSave(SslKeyHolder.java:251) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.ssl.SslKeyHolder.createKeyStore(SslKeyHolder.java:235) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.ssl.SslKeyHolder.lambda$createAndMigrate$1(SslKeyHolder.java:134) ~[appmanager-controller-2.11.2-plain.jar:na]
	at java.base/java.util.Optional.orElseGet(Unknown Source) ~[na:na]
	at com.dataartisans.appmanager.controller.core.ssl.SslKeyHolder.createAndMigrate(SslKeyHolder.java:122) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.ssl.SslKeyServiceFacade.<init>(SslKeyServiceFacade.java:43) ~[appmanager-controller-2.11.2-plain.jar:na]
	at com.dataartisans.appmanager.controller.core.modules.ServicesModule.sslKeyService(ServicesModule.java:32) ~[appmanager-controller-2.11.2-plain.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.30.jar:5.3.30]
	... 79 common frames omitted
```

**Comment by amittal89** [comment]
Hi,

Were you able to fix this?
I get exact same error on my ververica deployment

Thanks

**Comment by Sodki** [comment]
> Were you able to fix this? I get exact same error on my ververica deployment

@m-hristova for visibility.

**Comment by qinjunjerry** [comment]
@amittal89 We are checking this for you via the support case you opened. We will report back as soon as we have some findings.

**Comment by amittal89** [comment]
@qinjunjerry Thanks. Appreciate it.

**Comment by nacisimsek** [comment]
@amittal89 I have replied the ticket, kindly check and let me know your feedback through the ticket, thanks.

**Comment by amittal89** [comment]
Thanks @nacisimsek , I have updated the ticket with my comments..!!

**Comment by m-hristova** [comment]
@amittal89 @Sodki I didn’t fix the issue itself, but the problem turned out to be with Helm chart versions 5.7.1 and 5.7.2 (corresponding to platform 2.11.1 / 2.11.2), so I reverted to the release-2.11 branch and Helm chart version 5.7.0. That resolved my issue.

**Comment by nacisimsek** [comment]
Hi all,
The dependency conflicts causing this issue on Ververica Platform version 2.11.2 had been addressed by the platform version 2.12.0.
If there is no particular reason using this specific version, I kindly suggest you use a newer platform version. 
Here is the reference APP-Helm chart list for your reference:

```
❯ helm repo update
  . .

❯ helm search repo ververica --versions | head -n 20
NAME                               	CHART VERSION	APP VERSION	DESCRIPTION
ververica/ververica-platform       	5.10.1       	2.14.1     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.10.0       	2.14.0     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.9.4        	2.13.4     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.9.3        	2.13.3     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.9.2        	2.13.2     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.9.1        	2.13.1     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.9.0        	2.13.0     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.8.3        	2.12.3     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.8.2        	2.12.2     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.8.1        	2.12.1     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.8.0        	2.12.0     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.7.2        	2.11.2     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.7.1        	2.11.1     	Ververica Platform is the enterprise stream pro...
ververica/ververica-platform       	5.7.0        	2.11.0     	Ververica Platform is the enterprise stream pro...
```

**Comment by amittal89** [comment]
Thanks @m-hristova , @nacisimsek .
2.12 fixes the issue..!!
