### ISSUE TITLE
Flink version number ill defined in 1.9 image

### ISSUE THREAD

**Issue by cyrilou242** [ververica/ververica-platform-playground#21]
Hello, 

I'm trying to use the platform with a pipeline written in beam, so I'm using the image `1.9.2-stream2-scala_2.12` because flink 1.10 is [not yet compatible](https://beam.apache.org/documentation/runners/flink/).

When I launch a job I can see in the logs of the task-manager pod: 
```
INFO  org.apache.flink.runtime.taskexecutor.TaskManagerRunner      [] -  Starting TaskManager (Version: <unknown>, Rev:4d56de8, Date:30.09.2019 @11:32:19 CST)
```
In the logs of the job-manager pod: 
```
INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] -  Starting StandaloneJobClusterEntryPoint (Version: <unknown>, Rev:4d56de8, Date:30.09.2019 @ 11:32:19 CST)
```
Notice the `Version: <unkown>`

I then have a ververica platform event: 
```
Invalid Flink cluster version: (expected: 1.9)
>>> Invalid Flink cluster version: <unknown> (expected: 1.9)
```
And the job seems to be killed at this moment, next event, at the same second is  
```
Terminating a job due to an unrecoverable failure
```

When I try with the `1.10.0-stream1-scala_2.12` image, I can see the version number correctly, (but I can't use it with Beam):  
```
INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint        [] -  Starting StandaloneJobClusterEntryPoint (Version: 1.10.0-stream1, Rev:788c5da, Date:05.03.2020 @ 11:44:53 UTC)
```

Is there any way to fix this ? No problem if I have to build a custom image, but I'm not sure how I would be able to set such version number.

Also: I'm not sure if I should open this issue in this project, let me know if there is a better place for it.

**Comment by knaufk** [comment]
Hi @cyrilou242, 

thanks for reaching out. Usually this situation occurs for Flink 1.9 or earlier if the user JAR bundles classes of org.apache.flink.runtime (e.g. by bundling flink-streaming-java, flink-runtime or flink-java). This classes are provided by the framework and should not be bundled in the user code.

Could this be the reason?

**Comment by cyrilou242** [comment]
Thanks a lot for your quick answer @knaufk, this was the problem !
For those that may be interested, for beam I had to exclude 6 modules: 
```gradle
dependencies {
    compile("org.apache.beam:beam-runners-flink-1.9:$beamSdkVersion") {
            // passed by ververica image
            exclude group: "org.apache.flink", module: "flink-java"
            exclude group: "org.apache.flink", module: "flink-runtime_2.11"
            exclude group: "org.apache.flink", module: "flink-streaming-java_2.11"
            exclude group: "org.apache.flink", module: "flink-clients_2.11"
            exclude group: "org.apache.flink", module: "flink-core"
            exclude group: "org.apache.flink", module: "flink-metrics-core"
    }
}
```

Also, could it be that hadoop is also bundled in one of your jars ? 
I have hadoop in my fat jar and I have this suspicious error which makes me think there could be the same problem:
```
org.apache.flink.runtime.security.modules.HadoopModuleFactory [] - Cannot create Hadoop Security Module.
java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/HdfsConfiguration
	at org.apache.flink.runtime.security.modules.HadoopModuleFactory.createModule(HadoopModuleFactory.java:50) [flink-dist_2.12-1.9.2-stream2.jar:1.9.2-stream2]
	at org.apache.flink.runtime.security.SecurityUtils.install(SecurityUtils.java:64) [flink-dist_2.12-1.9.2-stream2.jar:1.9.2-stream2]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.installSecurityContext(ClusterEntrypoint.java:200) [flink-dist_2.12-1.9.2-stream2.jar:1.9.2-stream2]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.startCluster(ClusterEntrypoint.java:166) [flink-dist_2.12-1.9.2-stream2.jar:1.9.2-stream2]
	at org.apache.flink.runtime.entrypoint.ClusterEntrypoint.runClusterEntrypoint(ClusterEntrypoint.java:508) [flink-dist_2.12-1.9.2-stream2.jar:1.9.2-stream2]
	at org.apache.flink.container.entrypoint.StandaloneJobClusterEntryPoint.main(StandaloneJobClusterEntryPoint.java:110) [flink-dist_2.12-1.9.2-stream2.jar:1.9.2-stream2]
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hdfs.HdfsConfiguration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
```

Also, are your dockerfiles available publicly ?

**Comment by uce** [comment]
@cyrilou242 We don't bundle any Hadoop dependencies by default. Which Hadoop JAR(s) did you add to your image?

You get the error message, because Flink tries to create a Kerberos security context after it finds the Hadoop dependencies on the class path, but the `HdfsConfiguration` class is not found. Are you trying to use anything related to [Kerberos](https://ci.apache.org/projects/flink/flink-docs-release-1.9/ops/security-kerberos.html)?

---

The Dockerfiles are not available publicly. In order to find out which dependencies we bundle by default, you can run the following:

```
$ docker run  --rm registry.ververica.com/v2.1/flink:1.9.2-stream2-scala_2.12 -- ls -lah /flink/lib
total 127M
drwxr-xr-x 1 flink flink 4.0K Feb 20 16:19 .
drwxr-xr-x 1 flink flink 4.0K Feb 20 16:19 ..
lrwxrwxrwx 1 flink flink   50 Feb 20 16:19 flink-azure-fs-hadoop-1.9.2-stream2.jar -> /flink/opt/flink-azure-fs-hadoop-1.9.2-stream2.jar
-rw-r--r-- 1 flink flink  89M Feb 20 16:12 flink-dist_2.12-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   50 Feb 20 16:19 flink-metrics-datadog-1.9.2-stream2.jar -> /flink/opt/flink-metrics-datadog-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   51 Feb 20 16:19 flink-metrics-graphite-1.9.2-stream2.jar -> /flink/opt/flink-metrics-graphite-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   51 Feb 20 16:19 flink-metrics-influxdb-1.9.2-stream2.jar -> /flink/opt/flink-metrics-influxdb-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   53 Feb 20 16:19 flink-metrics-prometheus-1.9.2-stream2.jar -> /flink/opt/flink-metrics-prometheus-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   48 Feb 20 16:19 flink-metrics-slf4j-1.9.2-stream2.jar -> /flink/opt/flink-metrics-slf4j-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   49 Feb 20 16:19 flink-metrics-statsd-1.9.2-stream2.jar -> /flink/opt/flink-metrics-statsd-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   63 Feb 20 16:19 flink-queryable-state-runtime_2.12-1.9.2-stream2.jar -> /flink/opt/flink-queryable-state-runtime_2.12-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   47 Feb 20 16:19 flink-s3-fs-presto-1.9.2-stream2.jar -> /flink/opt/flink-s3-fs-presto-1.9.2-stream2.jar
lrwxrwxrwx 1 flink flink   67 Feb 20 16:19 flink-shaded-netty-tcnative-dynamic-2.0.25.Final-9.0.jar -> /flink/opt/flink-shaded-netty-tcnative-dynamic-2.0.25.Final-9.0.jar
-rw-r--r-- 1 flink flink  20M Feb 20 16:11 flink-table-blink_2.12-1.9.2-stream2.jar
-rw-r--r-- 1 flink flink  17M Feb 20 16:11 flink-table_2.12-1.9.2-stream2.jar
-rw-r--r-- 1 flink flink  63K Feb 20 16:12 log4j-1.2-api-2.11.1.jar
-rw-r--r-- 1 flink flink 258K Feb 20 16:12 log4j-api-2.11.1.jar
-rw-r--r-- 1 flink flink 1.6M Feb 20 16:12 log4j-core-2.11.1.jar
-rw-r--r-- 1 flink flink  23K Feb 20 16:12 log4j-slf4j-impl-2.11.1.jar
lrwxrwxrwx 1 flink flink   52 Feb 20 16:19 vvp-flink-ha-kubernetes-flink19-1.0.3.jar -> /flink/opt/vvp-flink-ha-kubernetes-flink19-1.0.3.jar
```

(Note that this is a bit different for newer versions of Flink which have separate plugins and a user lib folder.)

**Comment by cyrilou242** [comment]
Hello, thanks a lot for your insights !
I'm not trying to use Kerberos, and the hadoop resources are "deep" dependencies of other resources, I think to write into some GCS storage. (but they may be used for other purpose)

Just wanted to make sure I could safely ignore this message. 
Thanks again
