### ISSUE TITLE
An error when I try to upload a jar

### ISSUE THREAD

**Issue by neighborBoy0** [ververica/ververica-platform-playground#78]
Hello all,
I wanna upload a jar to the platform, but there was an unknown error, anybody has the same problem?

![image](https://user-images.githubusercontent.com/46868461/151644381-a21084c5-073b-487f-b91f-a8f9ee1930b8.png)

the log of container gateway:

`2022-01-29 02:40:23.455 ERROR 1 --- [<a name>-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.amazonaws.SdkClientException: Unable to execute HTTP request: minio.vvp.svc] with root cause

java.net.UnknownHostException: minio.vvp.svc
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[aws-java-sdk-core-1.11.951.jar:na]
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[aws-java-sdk-core-1.11.951.jar:na]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.13.jar:4.5.13]
	at jdk.internal.reflect.GeneratedMethodAccessor161.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[aws-java-sdk-core-1.11.951.jar:na]
	at com.amazonaws.http.conn.$Proxy161.connect(Unknown Source) ~[na:na]`

**Comment by knaufk** [comment]
Looks like minio was not installed succesfully. Can you check what pods are running in the vvp namespace and if those are up running and ready? 

kubect get pods -n vvp

**Comment by neighborBoy0** [comment]
Yes, the pod minio does not running correctly. I think the reason is that my coredns in the kube-system namespace is not running correctly. but I am not sure, I will try that again. But before that, I don't know why the coredns has 503 error, I had already turn off the firewall.

**Comment by neighborBoy0** [comment]
`# kubectl get pods -n vvp`
`NAME                                     READY   STATUS    RESTARTS   AGE`
`minio-544cbd598b-6fpmr                   1/1     Running   0          108m`
`vvp-ververica-platform-f9bbdf46b-82556   3/3     Running   0          102m`
it seems be installed successfully.

There are four machines:
my desktop: macOS 10.110.42.150
and the Kubernetes cluster was installed on 10.110.77.141(master), 10.110.77.140 and 10.110.77.139(the node ververica deployed)
so I create a new service to expose ververica to my desktop, just like this:

`# kubectl get services -n vvp`
`NAME                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE`
`minio                    ClusterIP   172.16.78.218   <none>        9000/TCP         107m`
`ververica                NodePort    172.16.115.54   <none>        8080:31110/TCP   25m`
`vvp-ververica-platform   ClusterIP   172.16.43.32    <none>        80/TCP           101m`

is that because the new service?
