### ISSUE TITLE
SQLLite table not created 

### ISSUE THREAD

**Issue by imalik8088** [ververica/ververica-platform-playground#84]
Hi there, 

I'm facing issues launching the VVP Community Edition following this installation page https://docs.ververica.com/getting_started/installation.html#kubernetes-namespaces

in the appmanager container within the vvp pod its facing issues with creating the table/database (local)

```
SQL: SELECT name, collection, value FROM appmanager WHERE collection = ?
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager ### Cause: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: appmanager)
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager ; uncategorized SQLException; SQL state [null]; error code [1]; [SQLITE_ERROR] SQL error or missing database (no such table: appmanager); nested exception is org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: appmanager)
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:92) ~[mybatis-spring-2.0.6.jar:2.0.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:441) ~[mybatis-spring-2.0.6.jar:2.0.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at com.sun.proxy.$Proxy100.selectCursor(Unknown Source) ~[na:na]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.mybatis.spring.SqlSessionTemplate.selectCursor(SqlSessionTemplate.java:200) ~[mybatis-spring-2.0.6.jar:2.0.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.apache.ibatis.binding.MapperMethod.executeForCursor(MapperMethod.java:167) ~[mybatis-3.5.6.jar:3.5.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:84) ~[mybatis-3.5.6.jar:3.5.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.apache.ibatis.binding.MapperProxy$PlainMethodInvoker.invoke(MapperProxy.java:152) ~[mybatis-3.5.6.jar:3.5.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:85) ~[mybatis-3.5.6.jar:3.5.6]
vvp-ververica-platform-7cf8f467cb-l9kh2 appmanager 	at com.sun.proxy.$Proxy106.findAllByCollection(Unknown Source) ~[na:na]
```
based on that comment https://github.com/ververica/ververica-platform-playground/issues/79#issuecomment-1061106908 I've also given the gateway and appmanager container more resources (2gi) but It didn't helped. 

Whats wrong? Why its not able to create a table/database with sqllite?

Trying it in my local k8s provided by docker-machine (apple m1)

**Comment by Myasuka** [comment]
Unfortunately, I also met this problem with my Apple M1 laptop. @imalik8088 did you ever resolve it finally?
